version: 0.2

phases:
  build:
    commands:
      - echo Build phase started
      - mvn clean package
  post_build:
    commands:
      - echo Build Completed Successfully
artifacts:
  files:
    - target/student-management-system-0.0.1-SNAPSHOT.jar
  discard-path: yes